[workspace]
members = ["mapack", "mapack-macros", "example"]
resolver = "2"

[workspace.package]
edition = "2021"
license-file = "./LICENSE"
repository = "https://github.com/00-team/mapack/"
readme = "./README.md"
keywords = ["mapbox", "mapbox vector tiles"]
categories = ["mapbox"]
